NODE_ENV: 'development'

SERVER:
  PORT: 3000

DATABASE:
  POSTGRES:
    HOST: 'localhost'
    PORT: 5432
    DATABASE: 'postgres'
    SCHEMA: 'bookstore'
    USERNAME: 'postgres'
    PASSWORD: '123456'
    SYNCHRONIZE: true
